development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_HOST") { "redis://redis:6379" } %>
  channel_prefix: chat_system_production
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_HOST") { "redis://redis:6379" } %>
  channel_prefix: chat_system_production
